name = "BAHH MINIGAMES 1.0.0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e72bcba945b757fc67b8cc739f71328f6bbdd1c5ec8f069ad0a239b032438ec"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
