name = "BAHH MINIGAMES 1.0.0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65e16aa05f1c9bf99a673a84cce207cc0f7023fc97d0dd8e7c25c488fd23fcca"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
